drop table perioxes;
create table perioxes (id integer not null, name varchar2(50) not null, lat number not null, lon number not null, clusterid number null);
drop table kentra;
create table kentra (id integer generated by default on null as identity, lat number not null, lon number not null);
drop able apostaseis; create table apostaseis (pid integer, kid integer, distance number);
drop table apostaseis;
create table apostaseis (pid integer, kid integer, distance number);
